### ISSUE TITLE
Add legend to report

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/parks-and-refuges-fev#15]
- [x] only include active layers on the map

Icons are in the image folder

**Comment by lprivette** [comment]
@ltmetz 

We had to refactor the way the layers work which unfortunately broke the legend in the report (i think) can you take a look and fix it if so?

**Comment by ltmetz** [comment]
I gotta rethink this a bit... Park Tracks and Interest Boundaries are formatted different than the other layers and I need to account for that...
