### ISSUE TITLE
Peak summary values in Active Layers not updating on event change

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/parks-and-refuges-fev#178]
**Steps to reproduce**:

1.  Click change filters and enter:
     site: 'Wright Brothers National Memorial"
     event: "2019 Hurricane Dorian"
     buffer: whichever
2. hit 'go'
3. note the values in the Active Layers legend for the peak summarys
4. hit 'Change Filters' and enter:
     site: 'Mattamuskeet National Wildlife Refuge"
     event: "Florence Sep 2018"
     buffer: whichever
5. Note how the values do not change
6. If you remove the '#FlorenceSep2018' from the url (so you're starting from scratch) and then do the Florence search you will see the values for that event

**Comment by 09Kathy** [comment]
duplicate issue from #172
