### ISSUE TITLE
Change 'Parks' category to 'Parks & Refuges'

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/parks-and-refuges-fev#18]
![image](https://user-images.githubusercontent.com/23640741/77560614-154ffc00-6e94-11ea-83d0-321800487226.png)

😬

**Comment by lprivette** [comment]
@09Kathy I'm not sure how to accomplish this one since this menu is populated by the USGS Search API https://txpub.usgs.gov/dss/search_api/2.1/doc/#overview (we're using the latest version here v2.1), but there may be some way to capture the element and change the name on our end. 

Give it the old college try and if a fix isn't apparent just post a comment here and move onto the next issue.

**Comment by 09Kathy** [comment]
Yeah, I'll poke around a bit more, but I took at look at it this morning and thought it might not be possible while using the USGS Search.

**Comment by kathymd** [comment]
Determined there wasn't a good fix without changing the code for the USGS search.
