### ISSUE TITLE
Redraw layers after running site report

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/parks-and-refuges-fev#216]
The layers get frozen in place after running html2canvas

@09Kathy I think you are already doing this elsewhere in the code so maybe you can reuse that, but correct me if i'm wrong. 

If this is too big a lift we may have to refresh the page after running a report

**Comment by 09Kathy** [comment]
I haven't been doing this - I think it was Lorraine who was using html2canvas? So I don't have code to reuse

**Comment by 09Kathy** [comment]
but I think it's fairly simple to refresh the page, if we want to go that route

**Comment by lprivette** [comment]
Refreshing the page for now
