### ISSUE TITLE
site report modal going off page and cutting off buttons

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/parks-and-refuges-fev#229]
site report: 
![image](https://user-images.githubusercontent.com/23640741/87449319-07e98980-c5cb-11ea-95a2-f2003bf766af.png)

This is isn't happening with the regional report modal

my browsers zoom was at 100%

**Comment by 09Kathy** [comment]
I don't have this problem (maybe different screen sizes?) but I think I fixed it in #213 - you can see if it works once it's merged
