### ISSUE TITLE
Drop DOI Regions and use layer region

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/parks-and-refuges-fev#246]

**Comment by HansVraga** [comment]
https://media.giphy.com/media/avkW4UabDdJFS/giphy.gif

**Comment by lprivette** [comment]
- switched fws layer used for queries from "FWSApproved" to "FWSApproved_Authoritative" because it worked slightly better with Turf.js
     - While attempting to transform the data for better performance and representation on the map, I was encountering many 
        data errors due to self intersecting polygons and nodes (coordinates) that were virtually identical. Which if I recall correctly 
        would make them invalid polygons (OGC?)I somehow remember this from college but can't find the right reference on their 
        website right now. Due to time constraints I'm not digging into this further. If we need to dig into this further this might 
        help: https://stackoverflow.com/questions/61926747/topologyexception-when-using-turf-intersect)
