### ISSUE TITLE
Refactor user experience

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/parks-and-refuges-fev#270]
When first arriving at the site the user will encounter a modal with an option for running a Regional Report or Site Report.

Clicking 'Regional report' will show the users the form and then act exactly as it does now, but the page will refresh at the end.

Clicking 'Site Report' will show the users the site report form and then two other options: 1) Explore map 2) Generate Report.
-  Number 1 will zoom them to the site with the buffer and layers on. From there users can pan around the map and explore the data. There will also be a 'Generate Site Report' button in the the top left sidebar under "EVENT: blah blah", so that when they're ready they can still print a report. 
-  Number 3 will zoom to the site with buffer and layers, perform the queries, and open the reporting modal so that they can download any data or reports they want.

**Comment by 09Kathy** [comment]
- [ ] Remove site and regional report buttons
- [ ] Move site report button to left sidebar above Map Layers
- [ ] Add Start Over button below site report button to take user back to Welcome Modal
