### ISSUE TITLE
Waccamaw error

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/parks-and-refuges-fev#294]
refuges, Dorian, Waccamaw, 30 km

print report and then click the console and you can see the error

**Comment by HansVraga** [comment]
What Event? Here is what I get:
![image](https://user-images.githubusercontent.com/12058013/90525042-69ee5f00-e134-11ea-9a27-2a8413378321.png)

**Comment by lprivette** [comment]
Sorry event was dorian, i updated the ticket
