### ISSUE TITLE
Populate filters

### ISSUE THREAD

**Issue by 09Kathy** [USGS-WiM/parks-and-refuges-fev#302]
John wants the parameters to be populated if he selected 'Explore Map' for one site, and then wants to explore a different site. I think the self-populating parameters went away when we switched out the Welcome Modal. Can refer to commits on Issue #221 to see how to do this.

**Comment by 09Kathy** [comment]
I just tested this several times, both on my local host the test site, and couldn't break it. All parameters auto-populate for me, even after just the first run. Maybe I misunderstood and he wants them to autopopulate after running a site report? If that's the case, we can't do that unless we store cookies or something, because the everything refreshes when the site modal closes.

**Comment by lprivette** [comment]
won't fix
