### ISSUE TITLE
Label csv according to event

### ISSUE THREAD

**Issue by 09Kathy** [USGS-WiM/parks-and-refuges-fev#308]
Now that we can select for 2 events in the regional report, and we are downloading 2 csvs at once, I think it would limit confusion to name the csvs according to their event.

**Comment by lprivette** [comment]
We're currently combining the peaks from both events into one csv (same for hwms. Since the event name is there, so they can identify what's what

**Comment by lprivette** [comment]
I think we can stick with that and close this issue unless they say otherwise
