### ISSUE TITLE
Fix undefined Flag Date in Regional Report

### ISSUE THREAD

**Issue by 09Kathy** [USGS-WiM/parks-and-refuges-fev#359]
We have catches for undefined values for peaks/hwms, but not the other variables. In this instance, the report doesn't run because Flag Date is undefined, but we should probably put fixes in so that any undefined variable will be caught. 

Steps to reproduce: 
![image](https://user-images.githubusercontent.com/46943254/92033622-9360da80-ed31-11ea-942f-15c8d6fe3704.png)

The report doesn't generate, and this error appears in console:
![image](https://user-images.githubusercontent.com/46943254/92033795-de7aed80-ed31-11ea-86cd-2cbcc441016e.png)

I think I've run the report with these parameters before and it worked, so possibly it's timeout related, but I freshly cloned the repo and tried several times without success, so my guess is that it is due to a undefined variable.

**Comment by lprivette** [comment]
Confirmed it's happening for me as well. And yes I've ran these exact parameters too many times to count with it working. 

here's the endpoint that returns all the HWMs for Dorian https://stn.wim.usgs.gov/STNServices/Events/291/HWMs.json. Doing ctrl + f i don't see any values for flag dates that are `null`, `undefined`, or `""`. odd.

It's something wrong with the maxDate variable that's beeing set on line 1579
