### ISSUE TITLE
Styles Suggestions

### ISSUE THREAD

**Issue by 09Kathy** [USGS-WiM/parks-and-refuges-fev#367]
Most of these are suggestions - if you think it's better as is or there's a better way, go with that! Also, if you think any of these comments are better suited for us to fix instead of you, let us know!

**Site Report**
- [x] Remove summary stats disclaimer when there aren't data
- [x] Remove storm tide disclaimer (Each site references a relative datum) when they aren't data
- [x] I think it would be better to have the sections with data uncollapsed when the site report loads. That way, if there is only one section with data, the user doesn't need to go through uncollapsing every section to find out if there's anything. Or perhaps we can gray-out/disable section buttons that don't have data? 
- [x] No data warning for Summary Data is larger than the warning for the other sections. Let's make it smaller. 
- [x] The cooperators would like the column headers to all be on one line (even if that makes us use the horizonal scroll bar). For example, for Max (ft), the (ft) would not be on the next line. 

**Regional Report**
- [x]  There's a colon after each parameter except Region. I vote we follow the Region format and remove the other colons. 
- [x]  Is the backward loader bar when we click 'Clear Selections' needed? If not, let's remove it.
- [x]  Disable peak checkbox until loader is finished (if it is clicked on before the report runs, the labels don't appear until it's been checked off and on)
- [x] Remove extra 't' character in Region selection box 
- [x] In the first table, Summary of Peaks, the title goes across the full modal. The other titles are constrained to the width of the first cell. I like the Summary of Peaks style better.
- [x] The cooperators would like the column headers to all be on one line (even if that makes us use the horizonal scroll bar). For example, for Max (ft), the (ft) would not be on the next line. 

**Geosearch**
- [x] Center supported search strings. Right now it looks like the line spacing is comparable to Word's 'justified' spacing, which in this case makes for large spaces between search terms. 

**Other**
- [x] Large peaks and hwm markers are squares in the legend, but diamonds on the map.

**Comment by 09Kathy** [comment]
- [ ] Largest peak icon and hwm icon in 'Active Layers' and Site Report legend should be diamonds, not squares.
- [ ] In the Regional Report, when there is a query with no data, put a period at the end of the warning (just because the first sentence has one). "Data are currently not available. Please try again later." 
- [ ] Either all selections should have colons or all should not (options in Regional Report and Query a New Site). I think it looks a little better without, but either way is good. (This was almost fixed 367-MoreStyles, but not all of them)

**Comment by 09Kathy** [comment]
- [ ] Remove 'Close' button from Filters modal (site query modal that pops up when you click 'Site' on Welcome Modal)
- [ ] Change the header of the Filters modal to 'Site Query'
- [ ] Remove the 'Query a New Site' button from the sidebar

**Comment by 09Kathy** [comment]
@mitchas , the updates look great! Just a couple more things I noticed:

- [ ] Ideally, horizontal scrollbar should be visible without scrolling down (Site Report)
For an example: Site Report with Site: Boston Harbor Islands National Recreation Area, Buffer: 30km, Event: Noreaster of March 2018, you need to scroll down in order to scroll to the right to see the end of the hwm table
![image](https://user-images.githubusercontent.com/46943254/94733834-fabc7b00-032d-11eb-97df-e0a144f21dee.png)

- [ ] A couple more colons are out there in the Site Report: 
![image](https://user-images.githubusercontent.com/46943254/94733898-1162d200-032e-11eb-9261-63e92b719973.png)

- [ ] The text in the box below 'Region' is cutoff in the Regional Report. It's supposed to say 'type', but just delete 'type' and leave it as 'Select a region'
![image](https://user-images.githubusercontent.com/46943254/94734074-4b33d880-032e-11eb-81f2-57fdbf68e767.png)

- [ ] I suggest replacing 'thru' with 'to' or a dash. It's not technically wrong as it is, but seems less professional.
![image](https://user-images.githubusercontent.com/46943254/94735112-d6619e00-032f-11eb-8d6a-7799671ffe85.png)

**Comment by mitchas** [comment]
@09Kathy Done!

The table scroll is a little better right now, but still not the best.

Ideally the header bar would lock into place while the part with the values scrolls - but tables are really hard to work with in CSS, so it might take a bit of work to get it to do that.

So for now I just set a max height for the tables in the modals.

**Comment by 09Kathy** [comment]
@mitchas The new table scroll looks really good! Everything else looks great too. Thanks for doing this all so quickly! 
@lprivette , should we merge these new styles in?
