### ISSUE TITLE
Create user for Kathy on 10.4 GIS Jump Server

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/parks-and-refuges-fev#374]
She needs access to this server in order to edit layers and publish services for the this project.

**Comment by aaronstephenson** [comment]
@09Kathy already has access. She has a WIMCLOUDAD account (`kdooley`), and all of our jump servers are connected to our AD.

**Comment by lprivette** [comment]
@aaronstephenson  we tried her AD without success. Sorry, I didn't record the error. We'll attempt again on Monday.

**Comment by 09Kathy** [comment]
@aaronstephenson , here are some screenshots with the steps I'm taking to connect. I might be missing something. 
1. Enter computer and username and press 'Connect'
![image](https://user-images.githubusercontent.com/46943254/93773973-52e4d600-fbe6-11ea-9ee4-443a7f46ea13.png)

2. This pops up and I enter my AD password (I've also tried selecting 'More Choices' and entering my pin)
https://files.slack.com/files-pri/T2PFUSXUL-F01AN36EQK1/image.png
![image](https://user-images.githubusercontent.com/46943254/93774280-b0792280-fbe6-11ea-93ad-f78c914ea49c.png)


3. I get this error:
https://files.slack.com/files-pri/T2PFUSXUL-F01AW3DL5QW/image.png
![image](https://user-images.githubusercontent.com/46943254/93774247-a9eaab00-fbe6-11ea-8453-97bb88793d4d.png)

I double checked that I have the correct AD password stored in my keepass by logging out of my laptop and successfully logging in with the AD password. I am connected to Pulse and have my entered my AD password both with and without my PIV card connected.

**Comment by aaronstephenson** [comment]
@09Kathy  WIMCLOUDAD is not the USGS AD. It is our own directory service in AWS.

**Comment by aaronstephenson** [comment]
@09Kathy WIMCLOUDAD is not the USGS AD. It is our own directory service in AWS.

**Comment by 09Kathy** [comment]
@aaronstephenson , what should I type in for the username instead then? I also tried GS\kdooley

**Comment by aaronstephenson** [comment]
You were emailed the full credentials when you were given you AWS account. If you don't have it in your keepass check you email.

**Comment by aaronstephenson** [comment]
Don't use the GS domain, that's the USGS AD.

**Comment by aaronstephenson** [comment]
It should be WIMCLOUDAD\kdooley or something like it.

**Comment by 09Kathy** [comment]
@aaronstephenson , thanks - I got it to work! I was using WIMCLOUDAD\kdooley , the problem was that I should have been using the aws password instead of my ad password

**Comment by lprivette** [comment]
@ka
