### ISSUE TITLE
Stream gage section in site report is only showing 3 graphs (the rest are there but off div)

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/parks-and-refuges-fev#376]
- [x] display graphs two to a row
- [x] increase that sections height to accommodate all graphs

**Comment by 09Kathy** [comment]
this started happening with Styles - it's listed in Issue #367 (but we could do it as a separate one too)

**Comment by lprivette** [comment]
Steps to reproduce from #367: 
1. Stream Gage Hydrographs get cutoff
2. Steps to reproduce:
3. Site
4. NPS
5. Prince William Forest Park
6. Hurricane Dorian
7. 50 km
8. Generate Report
9. open Stream Gage Hydrographs
10. Displays the first few graphs, but the rest are cutoff

**Comment by 09Kathy** [comment]
@lprivette , Earlier we decided to keep in gage names even if they don't have graphs associated with them. In this format, I'm thinking it looks better to keep everything one column to prevent big gaps (i.e. titles with a blank space to keep up the formatting where the graph should go) - what do you think?
![image](https://user-images.githubusercontent.com/46943254/94579510-87880b80-023e-11eb-8e9d-cf19fa766f99.png)
