### ISSUE TITLE
Region-wide summary warning displays when there are only peaks

### ISSUE THREAD

**Issue by 09Kathy** [USGS-WiM/parks-and-refuges-fev#389]
@lprivette , is this the same problem you fixed for regions with only HWMs in the last merge? 
![image](https://user-images.githubusercontent.com/46943254/95206135-eeac3f80-07ab-11eb-8863-9085ab22c088.png)
![image](https://user-images.githubusercontent.com/46943254/95206092-e522d780-07ab-11eb-9bbb-f32492d0bf5b.png)

**Comment by lprivette** [comment]
![image](https://user-images.githubusercontent.com/23640741/95221973-0690bd00-07c6-11eb-8aec-f5847e43d996.png)
I forgot to put `.length` when checking if there are eventPeaks lol
