### ISSUE TITLE
Regional report zoom to peaks is zooming to one peak when there are multiple

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/parks-and-refuges-fev#394]
Happens with the following fields selected: 
NWR, Southeast Region, 2020 Hurricane Delta, 50km

**Comment by 09Kathy** [comment]
Just started looking at this and it seems like the zoom is working fine, at least for those selections. However, I did notice that a peak was double-counted for those selections. Here the total count should be 2, not 3. 
![image](https://user-images.githubusercontent.com/46943254/97708563-ff886200-1a86-11eb-91d1-b30c5f55913e.png)
