### ISSUE TITLE
In site map show HWMs if there are no peaks and vice versa

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/parks-and-refuges-fev#419]
It's confusing users when there is data, but the map doesn't have any markers

**Comment by 09Kathy** [comment]
Do stream gages fit into this at all, or still do the hwm/peak swap regardless of those? Here's a site where we should show an hwm, but it does have a bunch of markers already
![image](https://user-images.githubusercontent.com/46943254/108543585-e3fdcd00-72aa-11eb-90a1-878ca6aecf31.png)

**Comment by lprivette** [comment]
goodness those labels. I think we still show regardless of the stream gages though. people might still be confused with seeing it in the data table but not on the map.
