### ISSUE TITLE
Create new bucket/sub domain for DOI FEV Production Application

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/parks-and-refuges-fev#433]
I tried creating it myself with settings equal to wim.usgs.gov bucket, but it says I don't have the correct permissions to configure the settings.

- [ ] should be called doi-fev so full name would be doi-fev.wim.usgs.gov

**Comment by fanguyc-usgs** [comment]
Setup doi-fev.wim.usgs.gov with the same settings as wim.usgs.gov. I think all the permissions were copied as well for accessing it.

**Comment by lprivette** [comment]
Thank you! 

It won't let me create anything 
![image](https://user-images.githubusercontent.com/23640741/112200320-7fa19680-8be5-11eb-8370-3eee793cca70.png)

**Comment by aaronstephenson** [comment]
@fanguyc-usgs you'll also need to create an IAM policy (just copy one of the already existing S3 IAM policies and change the resources) and apply it to Lauren's user account. You'll also probably want to create the DNS record in Route53 if the bucket is intended as a static web site.

**Comment by fanguyc-usgs** [comment]
Added IAM Policy and attached it to @lprivette 's account.
Let me know if you can create things now, and will this be a static website like https://wim.usgs.gov/ ?

**Comment by lprivette** [comment]
Sorry I should have responded to that earlier. So I don't 100% understand the boundaries of a "static" website. but it will be like our other mappers, FEV for example. Or the CBRS Projects Mapper ( https://wim.usgs.gov/cbrs-projects-mapper/) in the wim.usgs.gov bucket.

I tried uploading files both as a sub folder and directly to bucket but nothing is resolving. Just says "(failed)" in the status for doi-fev.wim.usgs.gov

**Comment by fanguyc-usgs** [comment]
I can see what you uploaded and I enabled the website at doi-fev.wim.usgs.gov

I wonder if this is related to the 500 issue error for the images in stn.

**Comment by lprivette** [comment]
That issue has never manifested itself in that way for this app. Usually it just show an error in the popup when you click on a site that has that file.

this is what I see 
![image](https://user-images.githubusercontent.com/23640741/112208665-fc853e00-8bee-11eb-9807-e95ab51e37aa.png)

**Comment by lprivette** [comment]
it's been deployed previously to test.wim.usgs.gov/doiFevTest

**Comment by fanguyc-usgs** [comment]
Does it have the same problems at http://doi-fev.wim.usgs.gov.s3-website-us-east-1.amazonaws.com/ ?
Might be a problem with how I did the routing.

**Comment by fanguyc-usgs** [comment]
@aaronstephenson did you ever have a route53 setup work on Firefox but not Chrome or Edge?
http://doi-fev.wim.usgs.gov/ works in Firefox but does not load on Chrome or Edge

**Comment by aaronstephenson** [comment]
Can't say that I have. Maybe something is wrong with the headers?

**Comment by fanguyc-usgs** [comment]
Looks like I need to setup cloudfront for the bucket to serve the static website. Stackoverflow pointed to this AWS article and all the other routes are cloudfront, IP, or pointing to an EC2 instance
https://docs.aws.amazon.com/AmazonS3/latest/userguide/website-hosting-custom-domain-walkthrough.html

**Comment by aaronstephenson** [comment]
All but two of our S3 websites are reverse proxied thru our Toad or Luigi EC2 instances.

**Comment by fanguyc-usgs** [comment]
Setup a reverse proxy like sparrow on Toad.
Works on my machine and personal pc, @lprivette please check if everything is working correctly https://doi-fev.wim.usgs.gov/

**Comment by lprivette** [comment]
Working as expected, thank you Chad!
