### ISSUE TITLE
Add real time gages to the report; include hydrographs 

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/parks-and-refuges-fev#47]
- [x] identify if there are realtime gages in the buffer or not
- [x] create section on report preview for real time stream gage hydographs. If there are no gages in the buffer then don't display this section to the user
- [x] If there are gages in the buffer, display their hydrographs in the "Report Preview"

we're using NWIS services to get that data currently and the function this occurs in is called `queryNWISrtGages`. And the graphing function is called `queryNWISgraph`.

![image](https://user-images.githubusercontent.com/23640741/81860623-00f3bb80-9535-11ea-9753-d4cc2c3e2a15.png)

**Comment by lprivette** [comment]
- [ ] identify if there are realtime gages in the buffer or not
- [ ] create section on report preview for real time stream gage hydographs. If there are no gages in the buffer then don't display this section to the user
- [ ] If there are gages in the buffer, display their hydrographs in the "Report Preview"

we're using NWIS services to get that data currently and the function this occurs in is called `queryNWISrtGages`. And the graphing function is called `queryNWISgraph`.

![image](https://user-images.githubusercontent.com/23640741/81860623-00f3bb80-9535-11ea-9753-d4cc2c3e2a15.png)

**Comment by 09Kathy** [comment]
- [ ] change link below hydrograph: 
https://waterdata.usgs.gov/monitoring-location/02231175/#parameterCode=00065

**Comment by 09Kathy** [comment]
@lprivette , for rt gages inside the buffer that don't have graphs, should we still include their name and site number in the report or leave them out?

**Comment by lprivette** [comment]
Yes, lets leave them in with the name and site number. that way they can go look up the gage if they still want to
