### ISSUE TITLE
create a legend where the layer toggles used to be

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/parks-and-refuges-fev#80]
here: 
![image](https://user-images.githubusercontent.com/23640741/82350181-05065a00-99c9-11ea-83bc-e495ee1aef51.png)

- [x] create legend
- [x] only display active layers in the legend

**Comment by 09Kathy** [comment]
Do we want to keep all the different color categories for every type of FWS interest boundary? We could keep those all in the legend - it just gets hard to differentiate when all the other layers are included: 
![image](https://user-images.githubusercontent.com/46943254/83803962-05624e80-a673-11ea-98a5-cb2c15de15ef.png)

**Comment by lprivette** [comment]
Dis done?
